# Generated by Django 3.1.2 on 2020-10-15 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('order', models.IntegerField(default=1)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='ludis_api.workout')),
            ],
        ),
        migrations.CreateModel(
            name='Drill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drill_name', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.IntegerField(default=1)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drills', to='ludis_api.section')),
            ],
        ),
        migrations.CreateModel(
            name='DrillModifiers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modifier', models.IntegerField(choices=[(1, 'Sets'), (2, 'Reps'), (3, 'Weight'), (4, 'Time'), (5, 'Rest_Between_Sets'), (6, 'Rest_Between_Reps'), (7, 'Distance'), (8, 'Intensity')])),
                ('unit', models.CharField(default=None, max_length=24, null=True)),
                ('drill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifiers', to='ludis_api.drill')),
            ],
            options={
                'unique_together': {('drill', 'modifier')},
            },
        ),
    ]
