# Generated by Django 3.1.2 on 2020-10-15 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ludis_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drill',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['order']},
        ),
    ]
