# Generated by Django 3.1.2 on 2020-10-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludis_api', '0002_auto_20201015_1004'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DrillModifiers',
            new_name='DrillModifier',
        ),
        migrations.AlterField(
            model_name='workout',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
