# Generated by Django 3.1.2 on 2020-10-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludis_api', '0005_workout_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drillmodifier',
            name='modifier',
            field=models.CharField(choices=[('Sets', 'Sets'), ('Reps', 'Reps'), ('Weight', 'Weight'), ('Time', 'Time'), ('Rest_Between_Sets', 'Rest_Between_Sets'), ('Rest_Between_Reps', 'Rest_Between_Reps'), ('Distance', 'Distance'), ('Intensity', 'Intensity')], max_length=30),
        ),
    ]
