# Generated by Django 3.1.2 on 2020-11-09 11:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ludis_api', '0006_auto_20201029_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('created_at', models.DateField(auto_now=True)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='ludis_api.workout')),
            ],
            options={
                'unique_together': {('name', 'workout')},
            },
        ),
    ]
