# Generated by Django 3.1.2 on 2020-11-04 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ludis_api', '0007_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='ludis_api.organization'),
        ),
    ]
