# Generated by Django 3.1.2 on 2020-11-11 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludis_api', '0008_auto_20201111_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='drillmodifier',
            name='quantity',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
