# Generated by Django 3.1.2 on 2020-11-16 10:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ludis_api', '0014_auto_20201114_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='code',
            field=models.CharField(default='PRINTNF', max_length=255, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]*$', 'Only uppercase letters and allowed.')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='ludis_api.organization'),
        ),
    ]
