# Generated by Django 3.1.2 on 2020-11-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludis_api', '0007_auto_20201109_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drillmodifier',
            name='modifier',
            field=models.CharField(choices=[('sets', 'sets'), ('reps', 'reps'), ('weight', 'weight'), ('time', 'time'), ('rest_between_sets', 'rest_between_sets'), ('rest_between_reps', 'rest_between_reps'), ('distance', 'distance'), ('intensity', 'intensity')], max_length=30),
        ),
    ]
