# Generated by Django 3.1.2 on 2020-11-14 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ludis_api', '0013_auto_20201114_2309'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('athlete', 'schedule')},
        ),
    ]
