# Generated by Django 3.1.2 on 2020-11-22 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludis_api', '0016_challenge_challengeresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='unit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
