# Generated by Django 3.1.2 on 2020-11-22 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ludis_api', '0017_auto_20201122_2032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challengeresponse',
            old_name='result_numeric',
            new_name='result',
        ),
    ]
