# Generated by Django 3.1.2 on 2020-11-22 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ludis_api', '0018_auto_20201122_2039'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='challengeresponse',
            unique_together={('user', 'challenge')},
        ),
    ]
