# Generated by Django 3.1.2 on 2020-11-23 08:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ludis_api', '0019_auto_20201122_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengeresponse',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
