# Generated by Django 3.1.2 on 2020-11-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludis_api', '0020_challengeresponse_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengeresponse',
            name='result',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=6),
            preserve_default=False,
        ),
    ]
