# Generated by Django 3.1.2 on 2020-11-25 14:17

from django.db import migrations, models
import ludis_api.utils.enums


class Migration(migrations.Migration):

    dependencies = [
        ('ludis_api', '0021_auto_20201125_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('COACH', 'Coach'), ('ATHLETE', 'Athlete')], default=ludis_api.utils.enums.Role['ATHLETE'], max_length=255),
        ),
    ]
