# Generated by Django 3.1.2 on 2020-12-02 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludis_api', '0022_auto_20201125_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drill',
            name='drill_name',
            field=models.CharField(max_length=300),
        ),
    ]
